project:
  type: website
  render:
    - "*.ipynb"

website:
  title: "Bash 스크립트"
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - auto: "*.ipynb"

format:
  html:
    toc: true
    css: styles.css
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: true
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"
